
# --- Object to be compiled ---

# String handling functions
obj-y += klibc/string/k_strlen.o
obj-y += klibc/string/k_strcmp.o
obj-y += klibc/string/k_strncmp.o
obj-y += klibc/string/k_strchr.o
obj-y += klibc/string/k_strrchr.o

# Math functions
obj-y += klibc/math/k_abs.o
obj-y += klibc/math/k_min.o
obj-y += klibc/math/k_max.o

obj-y += klibc/math/k_labs.o
obj-y += klibc/math/k_lmin.o
obj-y += klibc/math/k_lmax.o