DIR := klibc

# --- Object to be compiled ---

# String handling functions
obj-y += $(DIR)/string/k_strlen.o
obj-y += $(DIR)/string/k_strcmp.o
obj-y += $(DIR)/string/k_strncmp.o
obj-y += $(DIR)/string/k_strchr.o
obj-y += $(DIR)/string/k_strrchr.o

# Math functions
obj-y += $(DIR)/math/k_abs.o
obj-y += $(DIR)/math/k_min.o
obj-y += $(DIR)/math/k_max.o

# Long integer math functions
obj-y += $(DIR)/math/k_labs.o
obj-y += $(DIR)/math/k_lmin.o
obj-y += $(DIR)/math/k_lmax.o

# Memory functions
obj-y += $(DIR)/memory/k_memset.o