DIR := klibc

# --- Object to be compiled ---

# String handling functions

obj-y += $(DIR)/string/kstrlen.o
obj-y += $(DIR)/string/kstrcmp.o
obj-y += $(DIR)/string/kstrncmp.o
obj-y += $(DIR)/string/kstrchr.o
obj-y += $(DIR)/string/kstrrchr.o
obj-y += $(DIR)/string/kitoa.o
obj-y += $(DIR)/string/kstart_with.o

# Math functions
obj-y += $(DIR)/math/kabs.o
obj-y += $(DIR)/math/kmin.o
obj-y += $(DIR)/math/kmax.o

# Long integer math functions
obj-y += $(DIR)/math/klabs.o
obj-y += $(DIR)/math/klmin.o
obj-y += $(DIR)/math/klmax.o

# Memory functions

obj-y += $(DIR)/memory/kmemset.o
obj-y += $(DIR)/memory/kmemmove.o
obj-y += $(DIR)/memory/kmemcpy.o
