
#--- Standard Variables ---

DIR := drivers/input

#--- Object to be compiled ---

obj-y += $(DIR)/keyevent.o

#--- Sub directories ---

SUBDIRS := $(DIR)/ps2

include $(addsuffix /Makefile,$(SUBDIRS))
